import { translations } from './i18n'

// 本主题新增的少量界面文字，合并进上游的翻译表
const THEME_TEXTS = {
  en: {
    w2kLanguage: 'Language',
    w2kAppearance: 'Appearance',
    w2kAppearanceAuto: 'Appearance: follow system',
    w2kAppearanceDark: 'Appearance: dark',
    w2kAppearanceLight: 'Appearance: classic',
    w2kAdmin: 'Admin panel',
    w2kRegion: 'Region',
    w2kAll: 'All',
    w2kUnknownRegion: 'Unknown',
    w2kServerCount: 'servers',
    w2kLiveOn: 'Live connection active',
    w2kLiveOff: 'Live connection closed',
    w2kLiveConnecting: 'Connecting...',
    w2kHistoryRange: 'History:',
    w2kRealtime: 'Live',
    w2kHostInfo: 'Host information',
    w2kDetails: 'Details...',
    w2kLoadingSites: 'Loading server data...',
    w2kLoadingRemaining: 'Loading remaining sites',
    w2kLoadFailed: 'Unable to load server data',
    w2kRetry: 'Retry',
    w2kOk: 'OK',
    w2kError: 'Error',
    w2kLoginTitle: 'Login required',
    w2kLoginPrivate: 'This site is private. Please log in to the admin panel to view servers.',
    w2kHint401: 'The site is private or your login has expired. Log in via /admin#admin.',
    w2kHint403: 'Human verification failed. Refresh the page and try again.',
    w2kHint409: 'The database needs to be upgraded. Please ask the administrator to upgrade it.',
    w2kHint500: 'The backend returned a server error. Try again later or contact the administrator.',
    w2kHint404: 'The API was not found. Check that apiBase points to a CF-Server-Monitor Worker.',
    w2kAddServerSuffix: '',
    w2kHintNetwork: 'The request was blocked or the network is unreachable. Check CORS_ALLOWED_ORIGINS and the apiBase setting.',
    w2kCorsHint: 'Add this site to CORS_ALLOWED_ORIGINS of that Worker.',
    w2kUsed: 'Used',
    w2kFree: 'Free',
    w2kVerifying: 'Verifying you are human...',
    w2kStarting: 'Starting...',
    w2kUpdateAvailable: 'New version available',
    w2kCores: 'cores',
    w2kTheme: 'Theme',
    w2kViewCards: 'Cards',
    w2kViewRing: 'Rings',
    w2kViewTable: 'Table',
    w2kViewMap: 'Map',
    w2kMore: 'More',
    w2kLatency: 'Latency',
    w2kLoss: 'Loss',
    w2kLoad: 'Load',
    w2kSpeed: 'Speed',
    w2kUnlimited: 'Unlimited',
    w2kExpand: 'Expand chart',
    w2kCollapse: 'Collapse chart',
    w2kStyle: 'Style',
    w2kStyleCurrent: 'Style: {name}',
    w2kStyleDefault: 'Site default ({name})',
    w2kStyleWin2000: 'Windows 2000',
    w2kStyleXp: 'Windows XP',
    w2kStyleWin31: 'Windows 3.1'
  },
  zh: {
    w2kLanguage: '语言',
    w2kAppearance: '外观',
    w2kAppearanceAuto: '外观：跟随系统',
    w2kAppearanceDark: '外观：深色',
    w2kAppearanceLight: '外观：经典',
    w2kAdmin: '管理后台',
    w2kRegion: '地区',
    w2kAll: '全部',
    w2kUnknownRegion: '未知',
    w2kServerCount: '台服务器',
    w2kLiveOn: '实时连接正常',
    w2kLiveOff: '实时连接已断开',
    w2kLiveConnecting: '正在连接...',
    w2kHistoryRange: '历史范围:',
    w2kRealtime: '实时',
    w2kHostInfo: '主机信息',
    w2kDetails: '明细...',
    w2kLoadingSites: '正在加载服务器数据...',
    w2kLoadingRemaining: '正在加载其余站点',
    w2kLoadFailed: '无法加载服务器数据',
    w2kRetry: '重试',
    w2kOk: '确定',
    w2kError: '错误',
    w2kLoginTitle: '需要登录',
    w2kLoginPrivate: '这是一个非公开站点，请先登录管理后台后再查看服务器。',
    w2kHint401: '站点未公开或登录已过期，请通过 /admin#admin 登录。',
    w2kHint403: '人机验证未通过，请刷新页面后重试。',
    w2kHint409: '数据库需要升级，请联系管理员在后台执行升级。',
    w2kHint500: '后端返回服务器内部错误，请稍后重试或联系管理员。',
    w2kHint404: '接口不存在，请确认 apiBase 指向 CF-Server-Monitor 的 Worker。',
    w2kAddServerSuffix: '中添加。',
    w2kHintNetwork: '请求被拦截或网络不可达，请检查 CORS_ALLOWED_ORIGINS 与 apiBase 配置。',
    w2kCorsHint: '请在该 Worker 的 CORS_ALLOWED_ORIGINS 中加入本站域名。',
    w2kUsed: '已用',
    w2kFree: '可用',
    w2kVerifying: '正在进行人机验证...',
    w2kStarting: '正在启动...',
    w2kUpdateAvailable: '有新版本',
    w2kCores: '核',
    w2kTheme: '主题',
    w2kViewCards: '卡片',
    w2kViewRing: '圆环',
    w2kViewTable: '表格',
    w2kViewMap: '地图',
    w2kMore: '更多',
    w2kLatency: '延迟',
    w2kLoss: '丢包',
    w2kLoad: '负载',
    w2kSpeed: '网速',
    w2kUnlimited: '不限',
    w2kExpand: '放大图表',
    w2kCollapse: '收起图表',
    w2kStyle: '风格',
    w2kStyleCurrent: '风格：{name}',
    w2kStyleDefault: '站点默认（{name}）',
    w2kStyleWin2000: 'Windows 2000',
    w2kStyleXp: 'Windows XP',
    w2kStyleWin31: 'Windows 3.1'
  }
}

Object.assign(translations.en, THEME_TEXTS.en)
Object.assign(translations.zh, THEME_TEXTS.zh)

export const getLoadErrorHint = (trans, status) => {
  if (status === 401) return trans.w2kHint401
  if (status === 403) return trans.w2kHint403
  if (status === 409) return trans.w2kHint409
  if (status === 404) return trans.w2kHint404
  if (status >= 500) return trans.w2kHint500
  return trans.w2kHintNetwork
}
